### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Jinmeng-e** [Jinmeng-e/RainbowThreeMatch#1]
- [x] 업그레이드 시 블럭 개수 늘리기
- 일단 1000점 단위로
- [x] 깰 수 있는 블럭이 없을 때 리플레시
- [x] 종료 조건
- [ ] 팝업창 디자인 및 이미지 추가
- [ ] 배경 이미지 및 연출 추가
- [x] 터진 이후 어색한 애니메이션 수정 및 애니메이션 세부조정
- [ ] 플로우 (inrto-> 대기화면 -> 게임 진입) 
    - 인트로 이미지 랜덤 적용
- [ ] life system free max : 3, 10분에 +1
- [ ] 영구 플레이 3T
- [ ] 단계별 진동 3단계
- [ ] 로그인 (구글)
- [ ] 랭킹 (구글)
- [ ] 광고 바, 라이프 없을 때 구매 안하고 광고보고 플레이 라이프 +1
- [ ] 스테이지 표시
- [ ] 하단에 블럭 아이콘(enable disable) 추가
